In [3]:
import os
import pandas as pd

# Get the current working directory
current_dir = os.getcwd()

# Specify the folder containing the CSV files
csv_folder = os.path.join(current_dir)

# Get the file paths of all CSV files in the folder
file_paths = [os.path.join(csv_folder, file) for file in os.listdir(csv_folder) if file.endswith('.csv')]

# Create an empty list to store DataFrames
dfs = []

# Load each CSV file into a DataFrame and append to the list
for file_path in file_paths:
    df = pd.read_csv(file_path)
    dfs.append(df)

# Concatenate all DataFrames into one
merged_df = pd.concat(dfs)

In [4]:
merged_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,F96D5A74A3E41399,electric_bike,2023-01-21 20:05:42,2023-01-21 20:16:33,Lincoln Ave & Fullerton Ave,TA1309000058,Hampden Ct & Diversey Ave,202480.0,41.924074,-87.646278,41.930000,-87.640000,member
1,13CB7EB698CEDB88,classic_bike,2023-01-10 15:37:36,2023-01-10 15:46:05,Kimbark Ave & 53rd St,TA1309000037,Greenwood Ave & 47th St,TA1308000002,41.799568,-87.594747,41.809835,-87.599383,member
2,BD88A2E670661CE5,electric_bike,2023-01-02 07:51:57,2023-01-02 08:05:11,Western Ave & Lunt Ave,RP-005,Valli Produce - Evanston Plaza,599,42.008571,-87.690483,42.039742,-87.699413,casual
3,C90792D034FED968,classic_bike,2023-01-22 10:52:58,2023-01-22 11:01:44,Kimbark Ave & 53rd St,TA1309000037,Greenwood Ave & 47th St,TA1308000002,41.799568,-87.594747,41.809835,-87.599383,member
4,3397017529188E8A,classic_bike,2023-01-12 13:58:01,2023-01-12 14:13:20,Kimbark Ave & 53rd St,TA1309000037,Greenwood Ave & 47th St,TA1308000002,41.799568,-87.594747,41.809835,-87.599383,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
224068,F74DF9549B504A6B,electric_bike,2023-12-07 13:15:24,2023-12-07 13:17:37,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874702,-87.649804,41.874640,-87.657030,casual
224069,BCDA66E761CC1029,classic_bike,2023-12-08 18:42:21,2023-12-08 18:45:56,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874754,-87.649807,41.874640,-87.657030,casual
224070,D2CF330F9C266683,classic_bike,2023-12-05 14:09:11,2023-12-05 14:13:01,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874754,-87.649807,41.874640,-87.657030,member
224071,3829A0D1E00EE970,electric_bike,2023-12-02 21:36:07,2023-12-02 21:53:45,Damen Ave & Madison St,13134,Morgan St & Lake St*,chargingstx4,41.881396,-87.674984,41.885492,-87.652289,casual
224072,A373F5B447AEA508,classic_bike,2023-12-11 13:07:46,2023-12-11 13:11:24,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874754,-87.649807,41.874640,-87.657030,member

In [6]:
#check the shape
merged_df.shape

(5719877, 13)

In [8]:
#Reset the index
merged_df.reset_index(drop=True, inplace=True)

In [11]:
merged_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,F96D5A74A3E41399,electric_bike,2023-01-21 20:05:42,2023-01-21 20:16:33,Lincoln Ave & Fullerton Ave,TA1309000058,Hampden Ct & Diversey Ave,202480.0,41.924074,-87.646278,41.930000,-87.640000,member
1,13CB7EB698CEDB88,classic_bike,2023-01-10 15:37:36,2023-01-10 15:46:05,Kimbark Ave & 53rd St,TA1309000037,Greenwood Ave & 47th St,TA1308000002,41.799568,-87.594747,41.809835,-87.599383,member
2,BD88A2E670661CE5,electric_bike,2023-01-02 07:51:57,2023-01-02 08:05:11,Western Ave & Lunt Ave,RP-005,Valli Produce - Evanston Plaza,599,42.008571,-87.690483,42.039742,-87.699413,casual
3,C90792D034FED968,classic_bike,2023-01-22 10:52:58,2023-01-22 11:01:44,Kimbark Ave & 53rd St,TA1309000037,Greenwood Ave & 47th St,TA1308000002,41.799568,-87.594747,41.809835,-87.599383,member
4,3397017529188E8A,classic_bike,2023-01-12 13:58:01,2023-01-12 14:13:20,Kimbark Ave & 53rd St,TA1309000037,Greenwood Ave & 47th St,TA1308000002,41.799568,-87.594747,41.809835,-87.599383,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5719872,F74DF9549B504A6B,electric_bike,2023-12-07 13:15:24,2023-12-07 13:17:37,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874702,-87.649804,41.874640,-87.657030,casual
5719873,BCDA66E761CC1029,classic_bike,2023-12-08 18:42:21,2023-12-08 18:45:56,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874754,-87.649807,41.874640,-87.657030,casual
5719874,D2CF330F9C266683,classic_bike,2023-12-05 14:09:11,2023-12-05 14:13:01,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874754,-87.649807,41.874640,-87.657030,member
5719875,3829A0D1E00EE970,electric_bike,2023-12-02 21:36:07,2023-12-02 21:53:45,Damen Ave & Madison St,13134,Morgan St & Lake St*,chargingstx4,41.881396,-87.674984,41.885492,-87.652289,casual
5719876,A373F5B447AEA508,classic_bike,2023-12-11 13:07:46,2023-12-11 13:11:24,900 W Harrison St,13028,Racine Ave & Congress Pkwy,TA1306000025,41.874754,-87.649807,41.874640,-87.657030,member

In [13]:
#overview of the data
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5719877 entries, 0 to 5719876
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 567.3+ MB

In [14]:
# Convert 'started_at' and 'ended_at' columns to datetime
merged_df['started_at'] = pd.to_datetime(merged_df['started_at'])
merged_df['ended_at'] = pd.to_datetime(merged_df['ended_at'])

In [16]:
#check for null values
merged_df.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    875716
start_station_id      875848
end_station_name      929202
end_station_id        929343
start_lat                  0
start_lng                  0
end_lat                 6990
end_lng                 6990
member_casual              0
dtype: int64

In [17]:
# Check for duplicate rows
duplicate_rows = merged_df[merged_df.duplicated()]

# Print duplicate rows
print("Duplicate Rows:")
print(duplicate_rows)

Duplicate Rows:
Empty DataFrame
Columns: [ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual]
Index: []

There are some null values but no duplicate rows

### Dealing with Null values

In [20]:
# Extract rows with null values
merged_df[merged_df.isnull().any(axis=1)]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
105,3F624CAD11ADC36B,electric_bike,2023-01-24 19:15:35,2023-01-24 19:21:59,NaN,NaN,Greenwood Ave & 47th St,TA1308000002,41.80,-87.62,41.809835,-87.599383,member
106,7F4991C08F87A20F,electric_bike,2023-01-27 12:36:53,2023-01-27 13:02:30,NaN,NaN,Greenwood Ave & 47th St,TA1308000002,41.80,-87.62,41.809835,-87.599383,member
107,F3AD17CF04B88EE9,electric_bike,2023-01-20 00:37:00,2023-01-20 00:46:09,NaN,NaN,Greenwood Ave & 47th St,TA1308000002,41.78,-87.59,41.809835,-87.599383,member
108,CA3677FEF8FD11B6,electric_bike,2023-01-27 02:13:40,2023-01-27 02:18:22,NaN,NaN,Greenwood Ave & 47th St,TA1308000002,41.80,-87.60,41.809835,-87.599383,member
110,6FFD201EBB80C87C,electric_bike,2023-01-16 01:43:52,2023-01-16 01:52:02,NaN,NaN,Clark St & Elmdale Ave,KA1504000148,42.00,-87.68,41.990860,-87.669724,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5715933,BEE82452635B6FE4,electric_bike,2023-12-18 10:24:41,2023-12-18 10:34:26,NaN,NaN,Damen Ave & 33rd St,471,41.81,-87.68,41.834108,-87.675590,member
5715934,402B4754000FE2BC,electric_bike,2023-12-27 18:03:31,2023-12-27 18:15:38,NaN,NaN,Ashland Ave & 13th St,13354,41.88,-87.64,41.865234,-87.666507,member
5715935,E26081001B5C2E3C,electric_bike,2023-12-16 15:01:25,2023-12-16 15:09:55,NaN,NaN,Dayton St & North Ave,13058,41.93,-87.64,41.910578,-87.649422,member
5715936,A0252B843C8BF99E,electric_bike,2023-12-09 08:49:00,2023-12-09 08:58:31,NaN,NaN,Dayton St & North Ave,13058,41.93,-87.64,41.910578,-87.649422,member
5715937,94ECAC6EEEA1CDF1,electric_bike,2023-12-08 17:57:18,2023-12-08 18:03:23,NaN,NaN,Dayton St & North Ave,13058,41.91,-87.63,41.910578,-87.649422,member

In [21]:
# Fill null values in object-type columns with "not specified"
merged_df['start_station_name'].fillna("not specified", inplace=True)
merged_df['start_station_id'].fillna("not specified", inplace=True)
merged_df['end_station_name'].fillna("not specified", inplace=True)
merged_df['end_station_id'].fillna("not specified", inplace=True)

# Fill null values in float-type columns with -999 (or any other placeholder)
merged_df['end_lat'].fillna(-999, inplace=True)
merged_df['end_lng'].fillna(-999, inplace=True)

In [22]:
merged_df.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [23]:
# save the merged DataFrame back to a CSV file
merged_df.to_csv('merged_data.csv', index=False)